database: # 数据库配置
  host: localhost
  port: 3306
  user: minecraft
  password: password
  database: minecraft
  table: emotionsimulator
bStats: true
emotion: # 情绪值基本配置
  default: 5000 # 默认一段人生开启时所拥有情绪值
  min: 0 # 最小情绪值, 低于这个会抑郁致死
  max: 10000 # 最大情绪值, 高于这个会狂躁致死
  emo: 3000 # 低于这个会抑郁
  crazy: 7000 # 高于这个会狂躁
  emoAdd: 0.75 # 抑郁时提升情绪值的倍率
  emoTake: 1.25 # 抑郁时降低情绪值的倍率
  crazyAdd: 1.25 # 狂躁时提升情绪值的倍率
  crazyTake: 0.75 # 狂躁时降低情绪值的倍率
ore: # 矿物 (情绪值数值~时间(秒)~限制数量)
  iron: 25~10~2 # 铁矿(深层)
  coal: 10~5~2 # 煤矿(深层)
  gold: 50~10~2 # 金矿(深层)
  redstone: 15~10~5 # 红石矿(深层)
  lapis: 35~10~5 # 青金石矿(深层)
  diamond: 150~10~2 # 钻石矿(深层)
  nether_gold: 200~10~1 # 下届金矿
  emerald: 300~10~1 # 绿宝石矿(深层)
seeds: # 农田收获
  wheat: 1~1~2 # 小麦 Ageable
  potatoes: 1~1~2 # 土豆 Ageable
  carrots: 1~1~2 # 胡萝卜 Ageable
  beetroots: 1~1~2 # 甜菜 Ageable
  pumpkin: 2~5~1 # 南瓜
  melon: 5~2~3 # 西瓜
  cocoa: 5~2~1 # 可可豆 Ageable
animal:
  egg: 5~1~1 # FIXME:暂未实装
  mill: 10~5~1 # 牛奶
  sheep: 10~3~1 # 羊毛
  leather: 15~10~1 # 皮革
  meat: 5~5~1 # 肉类
  fish: # 钓鱼(FIXME:暂未实装)
    get: 5~10~1 # 每钓一条鱼
    treasure:
      low: 10~30~1 # 垃圾
      good: 50~60~1 # 牛逼的东西
plant: # 植物采集
  sweet_berry_bush: 5~1~1 # 浆果 Ageable
  sugar_cane: 5~1~3 # 甘蔗 Ageable
  cactus: 5~1~3 # 仙人掌 Ageable
  nether_wart: 15~1~1 # 地狱疣 Ageable
adventure: # 冒险采集
  materials: # 可炼药材料
    blaze_rod: 25~10~1 # 烈焰棒, 烈焰人
    gunpowder: 25~10~1 # 火药, 苦力怕, 恶魂, 女巫
    spider_eye: 25~10~1 # 蜘蛛眼, 蜘蛛, 洞穴蜘蛛, 女巫
    gold_nugget: 25~10~1 # 金粒, 僵尸猪人(?)(FIXME:暂未实装)
    bone: 25~10~1 # 骨头, 骷髅, 骷髅马, 凋零骷髅
heal: # 长时间处于满血饱腹状态
  per-tick-add: 0.01 # 每游戏刻所加情绪值
  time: 4000 # 多少游戏刻后
kill: # 杀戮
  player: -500~30~1 # 玩家
  creature: # 生物
    easy: -100~10~1 # 容易的生物
    easy-list: # 容易的生物列表
      - CAMEL # 骆驼
      - CHICKEN # 鸡
      - COD # 鳕鱼
      - COW # 牛
      - DONKEY # 驴
      - HORSE # 马
      - MUSHROOM_COW # 哞菇
      - MULE # 骡
      - PARROT # 鹦鹉
      - PIG # 猪
      - RABBIT # 兔子
      - SALMON # 鲑鱼
      - SHEEP # 羊
      - SKELETON_HORSE # 骷髅马
      - SQUID # 鱿鱼
      - TROPICAL_FISH # 热带鱼
      - TURTLE # 海龟
      - VILLAGER # 村民
      - WANDERING_TRADER # 流浪商人
      - PUFFERFISH # 河豚
      - CAT # 猫
      - OCELOT # 豹猫
      - SNOWMAN # 雪傀儡
      - DOLPHIN # 海豚
      - FOX # 狐狸
      - PANDA # 熊猫
      - POLAR_BEAR # 北极熊
      - TADPOLE # 蝌蚪
      - FROG # 青蛙
      - GOAT # 山羊
      - GLOW_SQUID # 发光鱿鱼
      - AXOLOTL # 美西螈
      - STRIDER # 炽足兽
      - BEE # 蜜蜂
      - LLAMA # 羊驼
      - TRADER_LLAMA # 行商羊驼
    normal: -50~10~1 # 普通的生物
    normal-list: # 普通的生物列表
      - BAT # 蝙蝠
      - IRON_GOLEM # 铁傀儡
      - WOLF # 狼
      - ENDERMAN # 末影人
      - PIGLIN # 猪灵
    hard: -30~10~1 # 复杂的生物
    hard-list: # 复杂的生物列表
      - BLAZE # 烈焰人
      - CREEPER # 爬行者
      - DROWNED # 溺尸
      - ELDER_GUARDIAN # 远古守卫者
      - ENDERMITE # 末影螨
      - EVOKER # 唤魔者
      - GHAST # 恶魂
      - GUARDIAN # 守卫者
      - HUSK # 尸壳
      - MAGMA_CUBE # 岩浆怪
      - PHANTOM # 幻翼
      - PILLAGER # 掠夺者
      - RAVAGER # 劫掠兽
      - SHULKER # 潜影贝
      - SILVERFISH # 蠹虫
      - SKELETON # 骷髅
      - SLIME # 史莱姆
      - STRAY # 流浪者
      - VEX # 恼鬼
      - VINDICATOR # 卫道士
      - WITCH # 女巫
      - WITHER_SKELETON # 凋灵骷髅
      - ZOMBIE_VILLAGER # 僵尸村民
      - ZOMBIE # 僵尸
      - SPIDER # 蜘蛛
      - CAVE_SPIDER # 洞穴蜘蛛
      - ZOMBIFIED_PIGLIN # 僵尸猪灵
      - WARDEN # 监守者
      - PIGLIN_BRUTE # 猪灵蛮兵
      - ZOGLIN # 僵尸疣猪兽
      - HOGLIN # 疣猪兽
un-heal: # 长时间处于非满血或饱腹状态
  per-tick-add: -0.005 # 每游戏刻所加情绪值
  time: 4000 # 多少游戏刻后